image: teeks99/clang-ubuntu

pipelines:
  default:
    - parallel:
        - step:
            name: Build and test
            script:
              - apt-get update && apt-get -y install cmake ninja-build
              - rm -rf build && mkdir -p build && cd build && cmake .. -GNinja && cd ..
              - cmake --build build --target amalgam 
              - ./amalgamate.sh
              - cmake --build build --target tests
              - cmake --build build --target amalgam_compile_check
              - cmake --build build --target cgamelink_compile_check
              - ./build/tests
              - ./build/amalgam_compile_check